# Generated by Django 2.0.7 on 2018-08-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0003_auto_20180808_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
