# Generated by Django 2.0.7 on 2018-08-13 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trelloapp', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projectmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.Project')),
                ('userid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='High', max_length=200),
        ),
    ]
