# Generated by Django 2.0.7 on 2018-08-13 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trelloapp', '0006_auto_20180813_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='userid',
        ),
        migrations.AddField(
            model_name='task',
            name='userid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Projectmember',
        ),
    ]
