# Generated by Django 2.0.7 on 2018-08-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0008_auto_20180813_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='userid',
            new_name='projectmember',
        ),
    ]
