# Generated by Django 2.0.7 on 2018-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0010_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
