# Generated by Django 2.0.7 on 2018-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0015_auto_20180819_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
